version: "3.9"

services:

  database:
    image: postgres:14
    container_name: movereis-pg
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pgdb:/data/postgres

volumes:
  pgdb:
    driver: local
